spring.datasource.url=jdbc:postgresql://localhost:5432/user_system_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver


# CONFIGURAÇÕES DO JPA / Hibernate

# update = cria/atualiza tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurações do Servidor

server.port=8080


# Configurações do THYMELEAF

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


# Configurações de log

logging.level.com.usersystem=DEBUG
logging.level.org.springframework.security=DEBUG
